const predefinedMessages = {
  hello: 'Hi there!',
  hi: 'Hello!',
  howareyou: "I'm doing well, thank you. How can I assist you?",
  goodmorning: 'Good morning!',
  goodafternoon: 'Good afternoon!',
  goodevening: 'Good evening!',
  bye: 'Goodbye!',
  thankyou: "You're welcome!",
  please: 'Sure!',
  excuseme: 'Pardon me?',
  yes: 'Yes!',
  no: 'No!',
  maybe: 'Perhaps!',
  seeyoulater: 'See you later!',
  whatsup: 'Not much, just chatting. How about you?',
  howsgoing: "It's going well! How about you?",
  nicetomeetyou: 'Nice to meet you too!',
  howsyourday: "My day is going smoothly, thank you. How about yours?",
  tellmeajoke: "Why don't scientists trust atoms? Because they make up everything!",
  tellmesomethinginteresting: 'Did you know that honey never spoils?',
  whatsyourname: "I'm just a chatbot, so I don't have a name, but you can call me ChatGPT!",
  whereareyoufrom: "I'm from the digital world, here to assist you.",
  whatcanyoudo: "I can provide information, answer questions, and have a chat with you. How can I assist you today?",
  whatstheweatherliketoday: "I'm sorry, I don't have access to real-time weather data. You can check a weather website or app for the current weather.",
  recommendabook: "Certainly! How about 'The Hitchhiker's Guide to the Galaxy' by Douglas Adams? It's a classic!",
  tellmeafunfact: "Sure, here's one: A group of flamingos is called a 'flamboyance.'",
  whatsyourfavoritecolor: "I don't have personal preferences, but I think all colors are wonderful!",
  howoldareyou: "I don't age, so I'm always here to assist you.",
  whatsfavoritemovie: "I don't watch movies, but I can recommend some great films if you'd like!",
  tellmeriddle: "Here's a riddle: I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I? (Answer: An echo)",
  canyousingasong: "I can't sing, but I can provide you with song lyrics or recommend music!",
  whatsthemeaningoflife: "The meaning of life is a profound question! It's different for everyone, but some seek happiness, purpose, or fulfillment.",
  dolikepizza: "I don't eat, so I don't have food preferences, but many people enjoy pizza!",
  tellmeafamousquote: "Certainly! Here's one by Albert Einstein: 'Imagination is more important than knowledge.'",
  whatsfavoritetimeofday: "I don't have preferences, but some people enjoy the tranquility of early morning or the beauty of a sunset. What's your favorite time of day?",
  howdobecomeabetterwriter: "To become a better writer, practice writing regularly, seek feedback, and read widely to expand your vocabulary and style.",
  tellmeaboutfamousinventors: "There are many famous inventors, including Thomas Edison (light bulb), Alexander Graham Bell (telephone), and Leonardo da Vinci (various inventions).",
  whatsfavoritedessert: "I don't have taste preferences, but desserts like chocolate cake and ice cream are beloved by many!",
  howdobecomeorganized: "To become more organized, create a schedule, use tools like calendars, and declutter your space regularly.",
  tellmeaboutfamousleaders: "Famous leaders include Martin Luther King Jr., Nelson Mandela, and Winston Churchill, known for their impact on history.",
  howdobecommoresed: "To be more confident, practice public speaking, set achievable goals, and believe in yourself.",
  consultation: 'Would you like to schedule a consultation?',
  legaladvice: 'I can provide legal advice on various matters. What specific issue are you facing?',
  caseupdate: 'Do you have any updates on your case?',
  billing: 'If you have questions about billing or fees, please feel free to ask.',
  contractreview: 'I can review contracts and legal documents for you. Just upload the file.',
  legalrights: 'Do you have questions about your legal rights?',
  courtproceedings: "If you're involved in court proceedings, I can provide guidance on the process.",
  evidence: 'Please provide any evidence or documents related to your case.',
  confidentiality: 'Rest assured, our conversation is confidential and protected by attorney-client privilege.',
  settlement: "Let's discuss possible settlement options.",
  legaloptions: 'I can explain your legal options and suggest the best course of action.',
  legalrepresentation: 'Are you looking for legal representation, or do you need advice for a specific situation?',
  nextsteps: 'What are your next steps in your legal matter?',
  };
  
  export default predefinedMessages;
  